# Copyright (c) 2026 KeelLinux maintainers
"""The spec's cloud section: this node in Keel Cloud (decision 0046)

    cloud:
      endpoint: https://cloud.example.org:8443
      api_key:
        file: /etc/keel/secrets/cloud_api_key
      entry_secret:
        file: /etc/keel/secrets/cloud_entry_secret
      set: shop
      ca_file: /etc/keel/cloud-ca.pem

keel only validates the section. The node agent of Keel Cloud,
keel-cloud-node of the keel-overlay-cloud package (`keel cloud`), reads
it, and writes what it learns into network.overlay.wireguard.peers, which
apply converges like any other field. The two secrets are references to
files, never values, and never `generate`: the API key is made by Keel
Cloud, and the entry secret by the set's first node, which shows it to
the operator so the other nodes can be given it.
"""

import re
from typing import Any
from urllib.parse import urlsplit

from keel.spec.fields import mapping_error
from keel.spec.validate_secret import validate_secret

KEY = "cloud"
KEYS = ("endpoint", "api_key", "entry_secret", "set", "ca_file")
SECRETS = ("api_key", "entry_secret")
# One lower case DNS label, as Keel Cloud names sets
SET_RE = re.compile(r"[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?")
PATH_RE = re.compile(r"/[A-Za-z0-9._/+-]+")


def validate_cloud(doc: dict, check_secret_files: bool) -> list[str]:
    cloud = doc.get(KEY)
    error = mapping_error(KEY, cloud)
    if error or not cloud:
        return [error] if error else []
    errors = [f"{KEY}.{name}: unknown key" for name in cloud
              if name not in KEYS]
    errors += _endpoint(cloud.get("endpoint"))
    joined = isinstance(cloud.get("api_key"), dict)
    if not joined and str(cloud.get("api_key", "")).lower() != "skip":
        errors.append(f"{KEY}.api_key: must be 'skip' or a secret mapping")
    for name in SECRETS:
        if name in cloud and (name != "api_key" or joined):
            errors += _secret(name, cloud[name], check_secret_files)
    if joined and "set" not in cloud:
        errors.append(f"{KEY}.set: required with an API key, the set this"
                      " node joins")
    if "set" in cloud and not SET_RE.fullmatch(str(cloud["set"])):
        errors.append(f"{KEY}.set: a lower case DNS label (a-z, 0-9 and"
                      " '-', at most 63)")
    ca_file = cloud.get("ca_file")
    if ca_file is not None and not PATH_RE.fullmatch(str(ca_file)):
        errors.append(f"{KEY}.ca_file: an absolute path")
    return errors


def _endpoint(value: Any) -> list[str]:
    """Absent means the project's instance; otherwise https, no path"""
    if value is None:
        return []
    parts = urlsplit(value) if isinstance(value, str) else None
    try:
        port_ok = parts is not None and (parts.port or 443) > 0
    except ValueError:
        port_ok = False
    if not port_ok or parts.scheme != "https" or not parts.hostname or \
            parts.path not in ("", "/") or parts.query or parts.fragment \
            or parts.username or parts.password:
        return [f"{KEY}.endpoint: an https:// URL with no path, user or"
                " query; Keel Cloud is TLS only"]
    return []


def _secret(name: str, value: Any, check_secret_files: bool) -> list[str]:
    key = f"{KEY}.{name}"
    if isinstance(value, dict) and "generate" in value:
        return [f"{key}: a file reference only: it is made by Keel Cloud"
                " or by the set's first node, never generated by keel"]
    return validate_secret(key, value, check_secret_files)
